/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_filteroptions_free: (a: number, b: number) => void;
export const __wbg_get_filteroptions_blur_sigma: (a: number) => number;
export const __wbg_get_filteroptions_brightness: (a: number) => number;
export const __wbg_get_filteroptions_contrast: (a: number) => number;
export const __wbg_get_filteroptions_grayscale: (a: number) => number;
export const __wbg_processedresult_free: (a: number, b: number) => void;
export const __wbg_set_filteroptions_blur_sigma: (a: number, b: number) => void;
export const __wbg_set_filteroptions_brightness: (a: number, b: number) => void;
export const __wbg_set_filteroptions_contrast: (a: number, b: number) => void;
export const __wbg_set_filteroptions_grayscale: (a: number, b: number) => void;
export const filteroptions_new: (a: number, b: number, c: number, d: number) => number;
export const init_panic_hook: () => void;
export const predict_disease: (a: number, b: number) => [number, number, number, number];
export const process_image_full: (a: number, b: number, c: number) => [number, number, number];
export const processedresult_normalized_tensor: (a: number) => [number, number];
export const processedresult_rgba_bytes: (a: number) => [number, number];
export const rust_zstd_wasm_shim_calloc: (a: number, b: number) => number;
export const rust_zstd_wasm_shim_free: (a: number) => void;
export const rust_zstd_wasm_shim_malloc: (a: number) => number;
export const rust_zstd_wasm_shim_memcmp: (a: number, b: number, c: number) => number;
export const rust_zstd_wasm_shim_memcpy: (a: number, b: number, c: number) => number;
export const rust_zstd_wasm_shim_memmove: (a: number, b: number, c: number) => number;
export const rust_zstd_wasm_shim_memset: (a: number, b: number, c: number) => number;
export const rust_zstd_wasm_shim_qsort: (a: number, b: number, c: number, d: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
